# Generated by Django 3.2 on 2022-04-06 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_sq_meter', models.IntegerField()),
                ('block_number', models.IntegerField()),
                ('entrance_number', models.IntegerField()),
                ('floor_number', models.IntegerField()),
                ('appartment_number_per_floor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(default='no owner', max_length=50)),
                ('purchase_date', models.DateField()),
                ('owner_birthdate', models.DateField()),
                ('status', models.CharField(choices=[('Buyout', 'Выкуп'), ('Incomplete buyout', 'Выкуп не до конца'), ('Terminated', 'Расторгнуто'), ('Not sold', 'Не продано')], default='Not sold', max_length=20)),
                ('room_number', models.IntegerField()),
                ('total_area', models.IntegerField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.block')),
            ],
        ),
    ]
